services:
  - type: web
    name: wisdom-high-school
    env: static
    buildCommand: ""
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

